### ISSUE TITLE
 (SystemJS) Cannot read property 'forRoot' of undefined

### ISSUE THREAD

**Issue by ghatul** [drusso85/ng2-scroll-to#12]
localhost/:58 (SystemJS) Cannot read property 'forRoot' of undefined
	TypeError: Cannot read property 'forRoot' of undefined
	    at eval (http://localhost:5555/app/app.module.js:92:47)
	    at Object.eval (http://localhost:5555/app/app.module.js:174:2)
	    at eval (http://localhost:5555/app/app.module.js:179:4)
	    at eval (http://localhost:5555/app/app.module.js:180:3)
	    at eval (<anonymous>)

**Comment by drusso85** [comment]
i never used SystemJS, can you suggest me any yeoman generator for testing the issue?
